apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: fbref
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:wqCYwXAdVEW3JW+/BCCzCMYrxjTmx1ITN0MrGRBnc7SdQEgBnnNAssXiob/txMyRlYsr9eORP6UhU7xzfSfCszt0Q9YaOjjcW+TDQ7f/+Kf2Hrp+9hWOM5AT9gbq1QnA451bUbHfuCpuNNHKba1PPaTXCIxaXU+85wbs+MWhTstFBPZ15SRo03xPjBCCWAJj+p17O9d+i4RonbrZ5YqeIBO/K6fJZZPD3FLCb+uYwE0ZAA8yfdeFErC9vrd7jN2BOpPpjqxPwGgCQ9DLe1Y04c+PZB4elsIEBe3lxYa3NTbL+SgT1FxShElkNTY=,iv:Y4cFoMcO2b1crqC4xwYryX0v1P6/E74b0N4ixJLXnK4=,tag:TJbxBHYyEh0UW3TGylxVJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bzdEZCs0VUg2RHcvcU9v
            cWxJRHBIZ05sbllPOXp6Z0FraDFRNXNDNVZRCi9RYS9lNjNFYnNUYjFydnBwSUU1
            Z1NVRmwybVo2cFA5aFlydUg1d0t2UFUKLS0tIDVJNEtneXF4aEhFYkxkL2tBeUVr
            STM3R1dxcHhDbEJGMVJxU2d4dkxnWEUKnGV0Jc21s+heZvWhEYo7ectAhvxELY/L
            rrl3U/HrGODec87cdtw1VvbUaf/m8XYU3bllDNBNE89OxlifUPR3/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T17:09:08Z"
    mac: ENC[AES256_GCM,data:vvEkWPSeWSBk+Leex/RBrKPpcM3hjAhp/asGa3zqb02XF88K7bfKk+vJrKS69QQMgr/P2LtYvKkjULLJIyThU9Xu1oHLFTwB/OKdy0A8zKfVvkDwCXfIcoaHSvnWfrt/J/Byg4pqgyTIh8bmW0LX5+PMGopqTXpAbF2nVW2NG+M=,iv:yPS57yDnphJMKTBE+r8tDgrSPxTKcIOCeppa7ttbKJc=,tag:otf+wjOb97Opj8fQYf6Avg==,type:str]
    version: 3.13.1
