apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:FFQaW4XQy+6babbJa1jhPBDEqB+26nol5v68zTAA6V9yX3ZZPd13OlZTDpQAXlSmNit9wBrXR5KK2oWLsNaQevXhRFWjEn5DRNke5SJYs70Sx5GMkL2mY/ONdj9xa4+sl4NwPidqx9vn1fA0DeLbCwuUxc9P5AqdGo4GO6/Muwf/FL5STCBmFMNiylQgiS28zru+GWVpNrVrvhTZtzM4VqjWfoLZV5caTzDNQqmU4NgkZagijA4N37a8gMOFLQAVaEHizOeqk0vIoUuNxKd9J8cDp7aCQKoLgdCWxPmbpImoKFB4NqFXHMIXGQdwMPhSNLDGXvEG+h0=,iv:569g/iKSxh/ZlplRUFaF1CwD1M1cA0TYcQa8khwbLTo=,tag:ImMfWVEDCPYlxJ+a7GXALA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VWZtNGpIMm83YWJXbHZU
            ejRwTm1DVDdnZ3VNbDNsd0U4Mis1N2pmUmc0CkdKZkl1cFA2amk2TGs3Q24vVE1a
            dWFMY2lEWXorSFlJQjRtODJabFZPN2MKLS0tIFBSWGxXT29oS1I4YmdWWkxoZUg5
            aEc2bk9KQWp4T1hwMUVxNnFQSUNLelkKCDf8n1r8djv+MUFO0SNewdJUCQZ77fDD
            L134cPB9zCpNdM6qc2sOszZpVABUm4jILTBcyrnS3U2sm+rHe8QACA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T20:13:57Z"
    mac: ENC[AES256_GCM,data:TdVXdQoCdgWx++5T+TPObxHliG6lEl4z48YeC47rKPTWLgyTg+lFQKaIYN+ehG/Yu8upGPKMr9o/uXuFbaET8GlKKxynTzW+1l/R2C6UHSsl0orjrYnMqOx3nR1OipzE9aRyDgxnBtUvbpZ3yLVY85ymc13wR71TmsR/AKnXM0E=,iv:e5+oUiVIz3Fk3p2bB52ydg53b/7cLddVvKXTl0+T+5A=,tag:Kjw1d82UbDMtX9BtbogPkg==,type:str]
    version: 3.13.1
