apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:OkGN86XTg7Ccc9wT/08xAEQX4tNxKyM05s+7Tf5BvUNThrM7Hig+890RTfQj2Fu8MxYc3gBKo6i0287Nh3iFu2nmozWmXSO+r94KWRVHBHkWkWx/f973k5ioIj8/OwnxZIjSSGTGMnGcS5Qf79NtqAhxS1MvKjWMTz2qnSUrODM7GFgHU//jIu4WZML2QCYYANWslSjsf61dHYDkBxpCUOmGKAX66QVvg0Pwg0ht9bimc6aolRnZ+Q==,iv:PLJVd7smSgsxb6wOIy4jaIJweMh094IbuHkiSV/14I4=,tag:zlEx4gRllySdZQuXffZTwQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VFRVRGQxdEN2Nmh6cVlG
            YytQak9nU0xXRFlTL043a0FrcUowRklRYkY0CmZxSXVMWUVqdWNxMzR1My90Vnlq
            WGtHN3JjLzJYUVNWSldsS2lsLzV6MzQKLS0tIGIxbWp4UUUwN1dBREZhRnhZaVFq
            UzB5eVBwMjVLYkZSTFVPemhmRGtMaXMKPipZrVGRmvjSDLmFKshSkDT+E77gAohD
            lR4SvxxGb3EO5ycHcWW9aKAoTuv+SBacT+dpPSowiaw313rJ8mUzJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heestkhtxgn5afg9jdww4dpxlk39qztjgcanu8pr4g8usufww36sdx732h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T13:13:25Z"
    mac: ENC[AES256_GCM,data:KN9wlw3561pSxlGZoPD+YxeXxGihhjY6p1X4mSD8QJ1Kc9V2DUoPloo9/hpXa07utsAC8Y6+TgW6OfIpfYJ10iDEZTgEv7Sav5xTC1WVxXIy61tfePLLwnbhGQLrO0ZVZwSF6C20d0RcZsJTsPfh7Dl1qhT2V0Id4A0RXB/Rnjo=,iv:O/Qai9QnnxwuXTPXQOXwe7oz73ITCw1ZYKOuBjA4Hfw=,tag:iDv6ppWWTAj9PlihVtrMyA==,type:str]
    version: 3.13.1
