apiVersion: v1
kind: Secret
metadata:
  name: nexus-root-password
  namespace: nexus
stringData:
  password: ENC[AES256_GCM,data:2SuMRG99EveO2iEDDmuuTIREd9c=,iv:7cbvnRiqKeEVKrupi8KkpuX3TnWDFx4MjQuLgPl2il0=,tag:XqxiGg9aE3TOiPP8Fj8kNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHpKcFBHUzlVVjM3ajB2
        YTJySkVRdjBUYWg4eTJTSHBzOWErVkZ1ZVE0Ck9td251T2tXUDY3M0VtbFVlNitw
        T0xmV2k4RXM5RSs4aU1hSVIwRTJEWTAKLS0tIDdLVmRCaEZVSWhwdjYxcU1wamh4
        V3JMcU14dFZmck45NDRYaHY4ZnRNVTQKwoU9pyDJ8ZrJsDOoEMyULyRTGi6K/9El
        OkIAUO0pvw7vjQrOyahrIkNjG+IC3VMhDrJL++w3RhA/dWCYflqHig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-04T06:39:09Z"
  mac: ENC[AES256_GCM,data:9lbp1zS3Skly2tWwb/NcunpR3VpaLJyZHxtqWQJF+ZfpcXe4w5yZZWQZh6WWT+ntUkeRnky9cZXuYnn/x4YQz1TcN977GwUT5j3qlWZ7jVZcV6KuARHGwxANBEZE4GuWV46cdKEz8nzZvJrSH9WXCzowOtPXjdJUFiCuKBbB8xA=,iv:/DljwoiIrc3CuPXPssoMvAKsKimToRHL3f0q7nRvau8=,tag:wlsf+85ijt3dTKc5u5TsgQ==,type:str]
  version: 3.13.1
