apiVersion: v1
kind: Secret
metadata:
    name: fbref-grafana-datasource
    namespace: monitoring
    labels:
        # Picked up by the kube-prometheus-stack grafana datasources sidecar.
        grafana_datasource: "1"
type: Opaque
stringData:
    fbref-datasource.yaml: ENC[AES256_GCM,data:XUn848EpcALCsyZOv0eM2mwuwygQDt1TyQrnpx+bTPX8yKc2hyhH0+7G0BKQtSv6iM0V6mkZiAblnDUYAzA64tKqgxlaLfagMOo3iFyApQoMijSDYb8UlW+NIgwRNUhrWRdCM0MVQz4U5d6BKJ5naUPnTSHZhgSd+ed9xD+vjZZToyA0zCdfpQmomTKFlylYI95FVtKlPGtpotpfjCGrCfJ2xw6/MeXnEULyj/edJodEJOMq7nvCaopdxPZH8d7nlTYMYhMBtYn8q/mHg8KizsxmdnJh6DXUeGlT07M8IP2CFtQqo7xOJBjG7+81VY9yPyKQZnZ2KidUJeB8SRrgxqzr5zdJylLodpAnfaapb9N/g3hFYH6ZcWBJh3aYsmMHbgJj87wu+qDepQWhZZ8Ur4ExW0HiVusr2KehkA7w1XEXwY+vxTpnGeghAn4oLiMcUr4jcusgIL8t4K47R8dkoC6bEWa+nzc/TPhu+YZVic3gw3eaVIxyG3R5KH4UgmNxRyCeFnnr3Eeu2xQvOu3hTfji62fuY7Wp/RCf/1gyiwJ1/1GheJn+Ic3LHnGDlJyDAs4TdkCIiGNliNm01BezZhBLgQ3T15np,iv:mynLq4N7uX1nl9XuJIA5DWfvSWpwvpawvWPRJSAMpx4=,tag:Wwr3TvJF7OJSpOlpRoDnbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR3FSUXZoS291VGttY1lz
            QWtLcS9RMUZ2dS90bkhDWEQ4ZUlVbTNBZEhzCmJsWVQzanBQR1I1bldkNlNIaWFx
            bnI3SnYxbE1lTkZuVU9Pc3F4WC8vTjgKLS0tIFUrQzkxQU54Z2ZoTWJlTFpONXlM
            NGZmQnEwdkkzLzcrdlBmd2J4TFhRNlEKtnbdOTDxbj6f1/lqfF4tnJKTpOw+R140
            dUqfNg5smEVZAW0R8K+sDybT07paHIqZcnoy8nGlD5KLX5przBjiHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T16:23:46Z"
    mac: ENC[AES256_GCM,data:jXF7hFfKk1sjB/2tNIkNPvCMkJjwNwg25B0pHOsinlzvh94ZdS60nmwUkSaIxnyOLS29XZ2ERj3v/kCnZQqOxOHMkwEpDjmaL/bJSMFuJMvzB0GWxA9ksmWS2I4qFqujWLX6NhxVWLio9UtHLbnDUicM6c8vNPCZ0AhjUrsC4Fs=,iv:qhTV9q0qi6jgHVPlAi+cqmhtRL90XAVagen7IP8Bp80=,tag:h0hKtwRbJk34eYYJKpP5MA==,type:str]
    version: 3.13.1
