apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
stringData:
    token: ENC[AES256_GCM,data:6y+auGjzra8OELZJy7U1N1wmpzFcK1dP1wqJVqDl6pr8ueCmm7kSTe2UsbpkEeCfj/lorLvyqGBw5HNXW1Od2rhOvp59HPuqWGiI7+l9KnoWgNv/aqMj4YdUWX2/Jqq+DomjMWu9DO4c398rJgyM9MUaZ5c7vz+0KQFayFB9hzFmw9I53oIv5MSinYoEoSQCSIPQMbwjzVe7RCTeRl93sx4SX2u8qIMyKt9irg+prJyGw772gCzUKA==,iv:nUZWGQg3VZpfCBm4cUs11ei1zBhuhO+FM/mf77u3AHg=,tag:cgIg7S11jgEYVRkDVSRsPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTEdKL0Q0RG5UMytKOC8z
            TXVrTVlSTTlYUStCWVBGTmoyZGExMGFhdW5NCjRFMFBvWStHK1NScE9CTlA3ZENU
            a3gvNjMwck9scll2MmlSa0JlZnZoZE0KLS0tIEp6OU54WWtUY1Vxb1JYL0pxK1Mz
            RGQ5SWpKZmJZNUlNN1V5dHlhOHdjaU0Koy7+RMUpndwvceyk0zO5+yCH5s+Dtl6W
            owV/S77ap0Ygj+99e1ho0YJSpq8OKBffj2cb52eAFE2qEMc1uEOZYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heestkhtxgn5afg9jdww4dpxlk39qztjgcanu8pr4g8usufww36sdx732h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T14:37:12Z"
    mac: ENC[AES256_GCM,data:uvdCQuUUdBeTiT0FdngnaXXRVqNLUfvmLkSTX9ZYPYAfa2QmJxgqTJ5mr2smrL70W2ynU91HS2YnGhHVyzhXZI+sUWinMgrrUl44RfztmObtBTeYHb9ZmrWGATyYriZVM3F7A5f2dZE1RMHD8V+OUBIOQlkM+BArerugaKIYpCo=,iv:OeKuXwjEpmXF3QcuCVfKhUXA5+VxXfPD5/VOFHaPFhY=,tag:K4VybDcJ3WfqZ9a63lm7Kw==,type:str]
    version: 3.13.1
