apiVersion: v1
kind: Secret
metadata:
    name: fbref-grafana-ro
    namespace: asp
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Uamfav0bjC2CVA==,iv:gQUSWyd7CqUwAbI1g6gGaGLyb0j+cGYyU/Gphg3cQak=,tag:3lA+POsW5maGHk8d2bKJ5Q==,type:str]
    password: ENC[AES256_GCM,data:yENV5fHie4Z+Et523kpsZ8pKararqN5tprJ21g==,iv:wpwf+HHLi5ZIS68lVfnc2nODPw1hKQt0ghsV7PV27II=,tag:Hew7TAf7T4FsHwYHtr+Fdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V0dXZEhWL1owZ09HZTRN
            K3IxNHB4ZTZvY1k1bEF3ZDUrcnlRMnhkTHhvCkZLTkJvT0toelh4UlVYZnpEUHFw
            TFgzYzBLVUE3MWxxTTMwcnpOS2JNQUUKLS0tIHdzUWhyMHA4ZDUycDZrZFJLUXpr
            aGdmV1NKQkwvdmRLOGNEbXEzWmpHcmMKNqhes/60F2Gtx0WlcMo4CKwYzNN4qF9q
            DM2EXRLi77VcTCEt77EH4nxfPMm6D7g6RgSxktzHfjlaKsT3qX0oVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T13:05:49Z"
    mac: ENC[AES256_GCM,data:jd0oaDYyHVzozPP8C/8C/c1SUtvbtLhHYj3qCUcc3QkqdBvdnXNMxGptEfziqfuKi77yaPaiff+95t3nIWUDAJ/NPs/rJqYQ1PiZDlo675BpojurgpQcHFJSkO7g1Il1MuxdrrMFWNjjBqQfTQ1KOyQgEsEKMG0IoNM9mIVPqhU=,iv:yRpXra12tztfjmWhnnS0+iNwdIbNII79oxrVYbQ79/Q=,tag:aXi1tSNoi3wZjwjYICqwqg==,type:str]
    version: 3.13.1
