apiVersion: v1
kind: Secret
metadata:
    name: fbref-grafana-ro
    namespace: fbref
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:MdfC+REvMavnLQ==,iv:4Mu+hfWNVkidpsi9w0CvvEg625x6Y+tB8cjVtSYkNdY=,tag:YHDYOaG3FVcM+TXAcLvEzg==,type:str]
    password: ENC[AES256_GCM,data:ST3vio8RT8MWCWk9++bxeNv0wf7jCm4OmM2hvA==,iv:QUeikXu3ejPJHmyEPtTA29W4jDjcjuUF60MUNH+fDDo=,tag:lLmwMbIfBmFWu7fqvn1wQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UlNzRlBDN1BhUzRNMkNX
            TEZIT3hTdXpUemxsVWtKaWg2Y0FZcmpOYmtBCmM2M1hHNmVSMkZIdXM0SFZLc0l2
            NXNSS09nZVE0c0ZiZWpHalJzZVBBeEUKLS0tIDhjZUdFM1h4UEVhazlLbU00TU9h
            WmhUZkl5OEI1OG5la0tFdGROa1NHZGcKbyEicSFNNzSARFwDz2x6pyt2xO+s6qtl
            PDBO6WFwiPU6nMuKkH66gJYLOMTGrrUzsX2qpnHdMP8o+Bpf6MtGoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T16:21:54Z"
    mac: ENC[AES256_GCM,data:2HGGeV7rrprHUvDbD8TaDzjMB30NLNo2J4DLEnwHfslhNmstogk1ZMMR8DYfOF7xSoxWcVpqYzddH9hcscTgfhoRwdDRmOtYRpOELGVqGtHo+UwSmcLhZia+wpPSrXtzA6aHXyoet6J6/aHWEyBLePNTs31heEgkNnSRz6cBtek=,iv:p6uRwYl84dZxg3YtGIQp/PezeblhdXeRpANeA6psvtw=,tag:4pIYWOtUNx05lKPyEH4gNQ==,type:str]
    version: 3.13.1
