apiVersion: v1
kind: Secret
metadata:
    name: fbref-nocodb
    namespace: fbref
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:HQNT3Uez,iv:cakyXF/lGUmJcvRhA9zZAJwkVB1F0d5gbG5RuotIVFs=,tag:gRb9mENqbVfMsGAr7fmyJg==,type:str]
    password: ENC[AES256_GCM,data:jcgursUTdqJMVOsI9JkFd5gXJK6krY1x1kkfrV8=,iv:5nkC4LoKx8YefxKRwy1CS8/zreDQ+pfJ3K+iiAJlmMA=,tag:xj8arxMlwAR9Kug8tW+bjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSWlaYXR0a1YySHVQb1NV
            WVd4SGVSOFByT3U5dUFyWnFNN1d4dXJjNFNJCkF0V3dad2J2cW9yUHQ0VmcrRmM2
            N2ZWYitTWDRRd2tQcjNESklEZXVnblEKLS0tIHVyUzVSQ0VGLzJ1ZUVxbnI0UHJQ
            VlFBYW5UVVVTR1B5UGF0M2QxcDBld3MKAzgD3O6nBVWmXtH1MPVSAFqoEdIFDp4X
            HEw18V8EznRvmQ5vbiRp162c+ziqc3yBxswDasSaXI/u5kyuk3ib1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T17:33:31Z"
    mac: ENC[AES256_GCM,data:rW2vRfoOwLUvAqnZSAbLH+OtqWL5xQ6pGf278QaCJyoIjiBHv8vp6qY3yqndezcXV0Vj/xXVjmhPvxGh+BeFxOo41Tf6TkBQAMg8REI2wC27IUbM7e6gRD6Q0JWz2WXpzrjP15JBLwqfPNXqxxLDPg70zkuFI4LhYT3OoVuYrdg=,iv:BGrNCSVALq8DWKRckFhd59onUNEVs/m5GapgZes/V7E=,tag:buG4HA68kmVgrFht+ZNwKw==,type:str]
    version: 3.13.1
