apiVersion: v1
kind: Secret
metadata:
  name: r2-backup-credentials
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:Ax6FAGplLsqJUMWR1XIkjoDiv6zCG55NPVXZoUYK+HY=,iv:XzcnTyprzTaRzNAhzTJuAyRatnZsESFz5kbWSHiE6L8=,tag:g6+e1eAVYz5e1i9tu/yaDg==,type:str]
  ACCESS_KEY_SECRET: ENC[AES256_GCM,data:TnRQXRw2Yv5E33r+ToshMKH11BczVtGUcMPpw4qPGLPZ2qRf7yp65Xk3OfjxQWuF6p9hgGCbi8C0SY5Ec5natA==,iv:37RkqtxQ5qjaQRoXVAPQvy63NEP94DMPcAkuHF+K5RI=,tag:+JOGexhxUcFi4q8hJKB0Rg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcXgwU2tWZGtnazVRbzQy
        TllIM3lBVjZNM0FPbjYrckZWMitUbDNhOFE0CjNxaGI1aEtTU2VaQng4ZHZXdWN6
        aldLdDJxbk9OT2ppc3dGcllqdU1CQ3MKLS0tIDU1Mis3anhPUEhqZVBrOWR5NVBU
        cHJmY0RrWVNoRFRTSE4zQzFEbHVIVzAKpnd+s7vDLUBs46ynRWuSH7eaV1sY+Kb9
        vRhEkvugBzz4lNrkD0sVhvGQRQSsDMWb5fVn/Qv04fiXw202oMRL2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T09:52:04Z"
  mac: ENC[AES256_GCM,data:sWVBp6Jke5NwOBpYpBm9RXlGXRSx4Se13qR7c2Gusx/D8m6QX89MlwT4Opav7K3udVBFpEU0Vp33DyCqbgNPix4xNLDmVtH3je7IT6O4ZuNTK1QY7guVlclILacL6VJki87pwvQIFxq46xNmXtnX9X1wJDILLr+WVRj74jxhU/8=,iv:uQdueUsOs0ono73u4Qr9QMkbAaUbrqJyvGkxekhY9KU=,tag:zkMB8CZ1Zam0UBS/w57RJw==,type:str]
  version: 3.13.1
