apiVersion: v1
kind: Secret
metadata:
    name: content-scraper-secrets
    namespace: asp
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:wnbNoYvp6Vh8Fmt9FQk2F9kiqcA9qztpm+jBjdjFQZTHlNUJBCSe3Rt5ma4r7I2toBxeG1DFXBAIA7sIJCRov4+skvFkeJ7mxNPcWQ==,iv:YXQkZv66+N3DDksNBDF6r1Q3JD8tGkZ7F5SbcTzj9L8=,tag:J0nG/H2DfvYoI0U1wB6Pjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZmxQRUFSeVo5M01haEla
            TDFnak1yNFlvV1RoeDVENFg3MnZCeU1taUdZCk0vODhFc2FqUzdNbnkvbEFKZDhN
            ckZhd1VQQnpSYWF5K3VxeTFTckZIZXcKLS0tIGVZdi8vM2FtQjJNSElKUytqb3Fz
            ZEoxQ0NPSGRXQzVBZi9lS0tOd01jalUKv/lq73LOXi0q9mFOKZuSHSzzQeeY19IL
            BUzE8zTK0+yRNgAK9C+pNqNnscO1Nl8i3oBvClLK2Q6gNFlY5v3lOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T09:07:36Z"
    mac: ENC[AES256_GCM,data:uZruiKc3FZGoM7cmASZbliT/kQT8WfKyvoj+jxGNi3QEnPDkjY7FXwGHHDoHflK7ly/hq6X3AX7VsKmKip2z3wJZSEgi1GLVnm9nZ1TDlouVW+/YtC5mx0fnumKLIthdfxN9hk0ZTBDqh04jNDgClTzbBSd885AArq3qdE5j6Ps=,iv:6SgC1V/zbNiErMxg1yoh0yWM53zm90zLOdH4norwp74=,tag:3J/xGdNxURaNOb9u9x2irA==,type:str]
    version: 3.13.1
