apiVersion: v1
stringData:
  username: ENC[AES256_GCM,data:M12wA3JUTg==,iv:8YL1BQL2PEKeVAO39uktWEpGdHIQPHVOx4oAoCSgh8E=,tag:dv/pq5ROXjp5BRIEguvpYA==,type:str]
  password: ENC[AES256_GCM,data:u+mo+xVcQKrQkbvT9REttZ0DUKH3BSVwEY8Mb8Rx,iv:oo1itPjyl8mwwRMLCZtrY7yhjY+UP5fJNKpIpDLUuC8=,tag:+i4idoeQJDgp08FXvB7Fzg==,type:str]
kind: Secret
metadata:
  name: asp-db-credentials
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMXpReVpuQ1dadlI4ZVJQ
        SERPek1NSW4rMzFQb1RENEhTenhPRUhjN1gwCkxEd3UraCtRbFVVYnhZTE90T0o5
        Q0pXUjRuUTlXVEhWK3E2dktSK2JBTzAKLS0tIGJ1Z25vcU9hei9nTDVOQVhpS2wv
        SnFPMEo3elBSOXJ1NnhQVzlrQ3dFSTQKvgazkkjdGgDpwMTQzTECnqGQkfW1m+PS
        TGWF9hH5C7ZYE9AuaPAfA6pozkBqS6rhh4vk5GmcL0dLpT2Zmy8HdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T15:29:58Z"
  mac: ENC[AES256_GCM,data:IXfowCVrXF3ZuP3P3hr6tqKvBDelde+/m7CLWlsP7tqpa56aXdZalmJIyjsfuQM6nFtEUtYtcUe1fUjn4mDb0sHrS9czxEYcNj0Gb4KkJbGcLg5dRNvXD9JbywPuVbMXRmlVeIoaYGrnjw+Du7hVUOslznKctp+YXR+KDPi1/7A=,iv:mJWFvUQCJGGtIoRjAiv3ryV8POMOt7Tc3RZcv4o7FL0=,tag:DVBbZjFPzX1N95Zu15k5UQ==,type:str]
  version: 3.13.1
