apiVersion: v1
kind: Secret
metadata:
  name: app-secret
stringData:
  username: ENC[AES256_GCM,data:Bi65tJE+WA==,iv:AEDs15a5bWmtrVs5O82S+1th91BnyexvFhEw+c2zvMM=,tag:PzIL1QdVzk7SvKmsUoDHRg==,type:str]
  password: ENC[AES256_GCM,data:vIEN5Xf6bfvo0MUl4FMl0Fxr3rDwvH3UM9cBoMjW,iv:0R4mWlvYwG1ihZfl+Z0zE5ez9l6Mmc1G5dpNf/SJ75c=,tag:Z8OoS01fBh8CNwdhvfNVUQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUGJER0FRMXlpRmRHZWdO
        bHhzUW1ZKzFYQmplTWxVWG84Y2IyWGQrYlFrClFlNDJDdGpzTXhkQmRmZnBJQjlk
        cHd5UFRCcjFuSmtNYWt1K3F3N29XbjgKLS0tIDlpVSthUVZRNkxHeTBHVmtLNFFx
        UElGc0FCY0dBcE12T3ltdGxROWI3bGsKrFEOxH1FuHVSHgm0DrXDepSkU7wphV3r
        /Tx6FEr4ALIRJKLYhPB394XJoIg8JjYLPp4UMoyYc+AZsV/xPBjHqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T14:53:31Z"
  mac: ENC[AES256_GCM,data:U4vy6+Vfrua0wKY884NjlxxXP8iq3q4Kz+r8P4uWfljZyFSYE+KdhtqzhzdJDURRIAZ4pbemeirLtpJy0BkpSNZ4JSGoXY4zaRY3Q5VvN4wX9Gc61aFR6pFQFytiAfQQUchu0Fd2UNmTfW14GszMFmw+9tuUVwfEf3BNzdUHQws=,iv:vNv8tNQktcluodA0NbB6uvc2M9qbiklTtnLkgfePCHo=,tag:sg9sQL7u6dImeVfxMR0bBQ==,type:str]
  version: 3.13.1
