apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-secrets
  namespace: asp
type: Opaque
stringData:
  admin-ui-token: ENC[AES256_GCM,data:vj2iMBjp+0+m61O9VXWQ2DeZ+yWBjsfnpJjZmCLSKw5ewXuDzY0z2PPHoBzLUyRK,iv:uIN1D2BSdoWfatgS70/VyUljz+ewAnZhS8HGXQPDDyQ=,tag:iEHD+nyRnR/I/k8y0vcT4w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYjFReGcxK3FMTGcxNXVF
        bHlyTDgyK2pmcDVzTTRtblEvTnRIdVJUL1cwCi9Pb1VPYjByVnpWQis3V3hNT0Nx
        eG5wckRJaFAvdDAwb2RrK0ZDMTNTUDAKLS0tIENlaTREMUtFSXB6b2N1cUJvdjNl
        RFF0clhmWU10WVZBb05qYUowSWtmZ1UKYXtAmpHrR13juJ9cQdCefg5LLu9G1P+w
        vHFrQ+VvLC2LUH7T4rNbOoKM6fyfqDkX0qY5gofHHZGi9bbTiOypRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T09:07:36Z"
  mac: ENC[AES256_GCM,data:DgEB5Ki8KqnN/nUwWPjprL5n7ObUZlrao7ngHcvIAmjN+zQE8ZvQiwEtjbVpBpC2pP5/BpryFpwffrWj3ez2esp2imQehtpwguxR0eP7pkhfM59AzrE4EhE3iArU/dc9acXlL9nCW7sPNhCwZBvCPkDTaRzqsvHEIXfqtzKKGNs=,iv:qqsjqA+Hu8aB88uZv4NdN4nnCOFx27NLXbIT3JkpRW4=,tag:HmPHt4OgXJz4oazKCjdoww==,type:str]
  version: 3.13.1
