apiVersion: v1
kind: Secret
metadata:
  name: asp-db-credentials
  namespace: asp
type: Opaque
stringData:
  postgres-password: ENC[AES256_GCM,data:zY3Mo4txModiz/pHJa07mUfUdoEy988drLjhuUgT,iv:eq02QNS0Wm/g8JhpV1lcseV5ivA/3EN44H2pTU0C47c=,tag:kxAmakp8XYYT3P9za69oSg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOclBOQkRoMVdGTFVuNFRR
        VkFVRnJwMEh5bzVpTEttZGhSdUtSYktWaGpnCit1MjAvamMyb3M5dlRNZ0VkY3FM
        YjdyK3REMERYTHMxY0N6VHU3b3N4NEUKLS0tIFl0NkFTNzdpazEvMER6TWZwWWt2
        c09BNlJZSm5DbmdkVGU1TkdobVBvQWMKol3pkQ0wGIgABBNmbVMugz+HttgVDs/o
        OrDSco6JjkIsAhgzsrqt7TRP1G/09mu55k1JUN7T82DD8eoFo1DOLQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T09:07:36Z"
  mac: ENC[AES256_GCM,data:QZMZi5rtaJQ+GvqpBkSahIqHP+vxqnGcjdz4qOhM3oFH62IEOg9GIaQjK1c1SCYRMAstEuS8HBmu+XOgPEckceQwJ6Jq2S5iIC/JDhVIhjGQwILneHTtb/EEKB9xoiSsq1eG4UAaVIXynxM8lbUTLanGCOkzm4ZaEDJpt7FYWSo=,iv:puWryaJlEaEYqH2acpQS1zvlmD3WHC82E+2lt2iijlA=,tag:MhNXA3gdICrbL+2Dmoi63w==,type:str]
  version: 3.13.1
