apiVersion: v1
kind: Secret
metadata:
    name: url-crawler-secrets
    namespace: asp
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:j76uIi98TifSGdy+wf0RZl83wNogTiYdHpqveKlLf4lvbzANzZAGxq9Y8E8EMuZlkWJD+Gkf0aYRKZ6/xZ9Pvcv0rWIDWnNdqAunmg==,iv:cdnt8iOSomNZhTCBGgM/YL4308iRQL8Oh+n5bFiacBs=,tag:3CCn04KuGm9QCNWnSjzeBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYkZrSS9qbWwzTXQvOTJ1
            VGM2WVNlOHl3M29YTmEwSXdKemh4VXBGOVJRCjMvWTc1Nnk3NE5tSkVRWDQvVytF
            ekFBN0hxY2FaOUVKWS95SWRVTSt4QjgKLS0tIEV3dzhNbHhsSkZuWGg5VzNvWGxp
            QlpXdUhuQlZLMUVxVlNwZU5EeURpaVEK3cUrIaLoevWnGrtqKQ3a4S1DCbTqh890
            aoa0lulX4dtvwQF4N1VkeX1QCtV7uasyM+UhmTn611AX2/eezH50mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T09:07:36Z"
    mac: ENC[AES256_GCM,data:ucXzlPwen2BwKH2eET65LMTkyoyf6RB3RHCgVOMSLdxvAkRtq+FAdAUr6Gs+6arq9taOGioAophJBizUtNnFNTJ+2ECVXONroOVQR54COlGIMYjSMizz6IM4Ydij/eRc/snC9d8x7tgUkXk0atwEIAMMtcDM9rOSWMZ+B5RRGQg=,iv:8vCPb5oFmH9ruvIGanv2Q+47qyqrc3UCQwFH6HXE76w=,tag:BMoETz8dqYK+FY/uQeL3nw==,type:str]
    version: 3.13.1
