apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: asp-db
spec:
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: r2-store
        serverName: asp-db
