apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: asp
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:WXS5eAVzDRaCTjraouObEW2RyOW+k/BzG0+3oacKJy/mYn8SCS5oF1hNlU94ad0+pbBVPx7NjP/ztdk94MtqNJ2yPYJtLbzq3flsY7OBQq74MtctbOVO82T8YXUSPKm7aB38cfcpeKJa3NHNmjxxj7VeHUc2vfNeoFFjHCNq96WMpSzNAt4vIMTINKpeRFTbiB+GZ4c47iMfuOqLf94HLbxqC2X4KwAY6n2dAElA5uqy,iv:auX9D+dH17R3/6kNOReiS6jTAOCZmA0mmDHQR20r3iY=,tag:78yHyDPWmbqwTubBPKPiRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cTk3NnVhUjNTbWNvTi80
            ajFEc3lFWWt3NVV1S05PcGcxdU5pMFM4R2xvCk1idkorTHMyQkZ0RnY2aWFJTG9h
            TEdaYlUvV0g3ODRvQnFOdExGNjlUVWsKLS0tIDQ5aWhKRUtqdFJJbERKWTdmSkZh
            YnhIUmFkTEs3cDJlODVLU2cxcWtXY2cK2RuBq8omnEp81zJxiSmVHXF2Q2ts9DcF
            lVsG4SV9iIpjWw7IsiwLuiMnK/VZnMH4oXNNqtyglYQWOoj/Py2/Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T10:40:56Z"
    mac: ENC[AES256_GCM,data:p1OW5kBlhS+R50KgB+glPXYw+OfVR3VT2lqnthI25+Bsx4B+sX8iSwJHZG97kl5IU3Dkd5gEh9JxqX/5v+4KNFlsow9aGp8031XrxSAbDuKNDYSBaNbdXyRXqnhZI2YxpY7S6SgWp/905r4t3eHkozo2Xr0DCKy7N7mJI5Y1cYc=,iv:kyacIuVcarh/htgd7UJhwC9F7sktZOQDwpLS9mXj1d0=,tag:8xy0VU7oF4GC/GR+msWvXQ==,type:str]
    version: 3.13.1
