apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VJZJh4DldtmELWae,iv:ce5shjB5OeZZ3YPAD9rRU0MQwhfIDlECRUbqXE//DvM=,tag:1s6ASXuZ8wS4fBqfkTDQgQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:xY6BzLPAzqjOV0Hw,iv:Y0582WtRcjNOuK3rrxPhaLAx6wm4B7V159xFy65EBOQ=,tag:2pW6aCIG+XSER9IMIDGfIg==,type:str]
kind: Secret
metadata:
    name: postgres-secret
sops:
    age:
        - recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcDdqRU5udVVxcEZnNUlW
            TGJsdExIbVd2c0k3Vlp2d1JoUEsycGZ2NXgwCkdiR3puWWYvV2xGRmhwSVhCZVV0
            SklpWTJtdGlDbnBobE10ZnhNdnRwWDgKLS0tIEUvS1NlRHZ6UnJZMldDZVc1NzJS
            RDZ0MVFnL1M3REhheVFrb3FoeDhjbzgK7VsrUK8yIBtVCvS0S4Bu+Aq5yFrJot5u
            4pVlDBYT5R8pZ+got+x8RJwFG46JPusoVQP7ohtPouVUUTYoYP7Nkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:31:52Z"
    mac: ENC[AES256_GCM,data:JIKkJIEkYqQXpXy+WlTYiyV+qQxu0okc9+tuf//lQd9ObL/TuOaYZmK3EFZBPf9q9pqUxzSN57QaVuDJSp9QtI1FkMS+/f98tpcqG2DDvn4RlDsl6/7s0yfcu053N9589joZRC7re8m+2a0qWopKd7V4wGQ8VGvhgX9cSiOKAYY=,iv:edA6agleumP6zwqUavVSn99WAJbRDSO+eASK7LEJ+S4=,tag:d81O2vck1DjBOsZEglDdoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
