apiVersion: v1
data:
    stringData: ENC[AES256_GCM,data:3pIugT6L4WnGj8Bl8qWTYTHIHBkdboalNCXaOuEGLnKfMUtj/H7DaCErRj4R2oMj/TZmBw2WFn7gx2ktmKof26gehZZ7d709Qk+l+xGg74sylABGxuN6949z/gdhdeaDCmfClUzr8ubZ90sPGHLEDwl+nBxCICqcmc21E9STlKFSkeIx15fbocQ9CSobDrcCTrvd00to/7k5HVQ33FskIhtuGulrQvsOpG9e1DliJ8Qw0yFlG+cTSMrz9YOgBH87Yxb2eHqWCAItBneynaji3QjqZvUosyDpvSaFejVNkDA1SXfKliuK+V4yaOfcFUJgSJWGNYhIzjc=,iv:7LaYs0yHHXVzNg7of+r280Vc4Wa+FIV+ZT3o2C1JGvQ=,tag:vr0jgdDP8W9h571U8EYjyQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5b1luM09idUJYdVNZSC9q
            RHI1MldibTM2NW9RcS9sNXc5bHF0RC84c1dZClBFcTl1WTYrb2RVWFcyWFN5MGhW
            endwaTZkNkhYS2lYeEhNMlBtQUZsWGsKLS0tIGlYWTU3OFo2U1BTQm9mVHhPRjF4
            Z1FjejlGY3kxZGZVWTh0U05Ja0NwdVUKNvqA92zq2QzJMPJx+QPe/uyMv/mSmJfI
            AfCMKNcAfddoZJpY17Hqr3BvEKIeH38TX0pZZr7xm6kiy8R41w//kQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T19:59:05Z"
    mac: ENC[AES256_GCM,data:CrPD5Yo6xZbpunRoIInIOSkqLlLVXsYbVHxW4MwXijWIE6Y60SQ2/HRm+8YTnZsxkirUVnjpMUKGpb2WeUICGgtW3kcX2GoBe8WVuFHjgaUj0UDPGUAczLorbK9daO0IWUv/0r6ll6XSSDccZd0MA8Cy4LVPBNLBEkF2OLJ/hNs=,iv:lO4Zq2+v0sMsG+G/dY1p08suj6mbDcsXVAQMGN4piwI=,tag:YA9AOk8+7xu2MWf5sza7fw==,type:str]
    version: 3.13.1
