apiVersion: v1
data:
    MYSQL_PASSWORD: ENC[AES256_GCM,data:0WVEEsFWTXY=,iv:gXdyBmM+xC8G2t3qE5gFh1TZu21Kop136bfz4mVH0po=,tag:D5CvPxbYKMSG4AAnzuCsCQ==,type:str]
kind: Secret
metadata:
    name: glpi-db-secret
    namespace: glpi
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTFFuK1Z3VVJJaTdkQnBF
            dzZvL2pXUU56Q3pUM1BpeTVVYjd5Qi9DOXh3CjN4OE5udkVmM3grUUY2SHdlZGJ4
            MjJvTmNJMERhdkswQ1kvVVFJU054QWMKLS0tIE40Y1ZjU0FrellXTFFNVXFabHMy
            VllJTHQ4b2UvZHZtbHVIQzFUYjRjV2sKDsPS76W6WoFJebFTCDKaXuXyOrJPd5KY
            FtSP5hDSauqbXLVCkcCXLilGHyaDOBa+l0zNVmiYGjrXeEj9DG0jsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heestkhtxgn5afg9jdww4dpxlk39qztjgcanu8pr4g8usufww36sdx732h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-27T18:40:31Z"
    mac: ENC[AES256_GCM,data:WIRI8cq+Ri6pW8/q9yEo4ynsPO7cBlgul655flIAsMmZSnlwWV9JprdGyH+gXb0Rrn9gPXZoAENT5aovLd6GBJNI7ohqfgmnMY7gZhyKORSEU38lixbCWB/1j9g7RJJzyWUYQqtwgHhaHMZh6PTnq3jWOnFIUyCyq4fhEy1nrt8=,iv:A9NIwEngAqebgZGkNBm3Y2tEXsrVIKmYblpnRCBiaz0=,tag:uCqA7LkKKWztOioemrkJHQ==,type:str]
    version: 3.11.0
