apiVersion: v1
kind: Secret
metadata:
    name: r2-staging-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:KK7wPABV8VxwC3Z7Wfyy9cjH1NJj9CLYxbnZKDLKCpU=,iv:P+8oOm5Pm20Wh9hLuskOJWtpploKFD9FDv4D9Ytaww4=,tag:CTKOP3dcMrVrIJizhdhMkw==,type:str]
    ACCESS_KEY_SECRET: ENC[AES256_GCM,data:5s4tqq5V87zDxe7xv6mAViL1K/WoeKtPH2wXRNlID9fbP6CCJ1qDjwz5P0YHxokdUXKTsJioDk+5ff3WGTjAAA==,iv:cUAWpn+PekGiNmsE2gOSoxMiV7YUoAgoJLBwVidkRUE=,tag:x8F2CYIuo3Hjm8UdXxXfCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSVlIRG55NU13bFVTQmE0
            bkEyWVJYSlUxWWZoOGdXVk1Fd1VnbUlHVTN3CmsybjdCRVlVZ3VDNTl0QzAwTUoz
            U1ZrdDIwQ1NEQ1oyYzhoUjFDRWNYNDQKLS0tIFI3QjNQODRvR2g0S1liLzAvZzhl
            dUpXNS9FRUF1UHZsWGQrZUlpWGdKc0UKrtxkBUgAug7pDGlNFWDtk+CJzRsapBs8
            /mktubZmFf/q4bST/i0tvflGI2Aahh/rrdeJGPos4F2/b4SL+6qHJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heestkhtxgn5afg9jdww4dpxlk39qztjgcanu8pr4g8usufww36sdx732h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T15:52:29Z"
    mac: ENC[AES256_GCM,data:YVxEhuOI1hQJ8JXnGvN5E9zgu0RINrPHrmfarGMohca5qDtlcD3ZaIRsytyYp64XDEXn6Z6ZSIDa9W6n8LqcVLyRLLom2BqYstEX2JZ7D+NEaEZ2AoV1+/oa7aBCmd0fsABIbVfppjFAeOr4Hx+ODBRcIItT3zjzOU1RtdxPRMw=,iv:47Wal2OSD89WpNmQbBUwWQqPNqqOg8REIVsVY6C5Sc8=,tag:2knwxA0xMcUZvWs+ZKqRcQ==,type:str]
    version: 3.13.1
