apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-failures
  namespace: flux-system
spec:
  providerRef:
    name: telegram
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: "*"
      namespace: flux-system
    - kind: HelmRelease
      name: "*"
      namespace: asp
    - kind: HelmRelease
      name: "*"
      namespace: monitoring
    - kind: Kustomization
      name: "*"
      namespace: flux-system
