apiVersion: v1
data:
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:vC2itcuvlKo=,iv:buhGzd1g0/wXRm9C9M1QUrVSWumaSIP8HBr5WkZIHPo=,tag:UaI2Aam/jqirPU3lHa/d7A==,type:str]
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:2GFWpgb7qYM=,iv:smA8l8NTgr0b1MW4cdb4gMgr0yEqg3wNzK54EEYhwuo=,tag:f5uD5BRI1ZADfs3c/zUVsQ==,type:str]
kind: Secret
metadata:
    name: keycloak-secret
sops:
    age:
        - recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHV5YTlLQWVvVUZOc1M2
            TkYwc1lvSTZoK0UzaEpLbmZ6YStOdjVLaUg0CnE4aGN4SWoybGNueWU1NDBKZWp2
            Z2RLQXoveFRTQTlLdGdtRCtnYWRtNnMKLS0tIDNUbGlWd0xCZXZIOGJlYlpDWE1P
            T0VLNjd3WGplVDgrRXhwOXdBZWZkdE0KhIKJxR+UOs1U/jgoQRFl/yL4eYG19O8w
            TxaqKJKmkCKIcJW8tIMkgsQAd5b3mxPL51HgDxfZKoFNdMnUAhWkNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T15:45:03Z"
    mac: ENC[AES256_GCM,data:i7tkSNxCVQL9YZkZmJCkwd0l3xVwEum4ceUzJaClwAhGbYPnbNabfkuQKtz6HWOUqodYTJrTV/PyXM7s1x3yJdKIQ/3WAm5Gs+Kjx0vMITI+JsENdMLl1rGiSG6oGLondkdeOmN3BPoDiM1Z6Z8P2+iHuDYTc2UuR2nhjanGGH8=,iv:aEHNmFzFoj/pzJSntvs9eG8hXIBLStW8quiFfHKFj3c=,tag:WQfMIOwFe9lefVx/id/1HA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
