apiVersion: v1
kind: Secret
metadata:
    name: arc-github-pat
    namespace: arc-runners
stringData:
    github_token: ENC[AES256_GCM,data:SBO0mlx/Gs7WQ1oD2dpe9WDraCoiiNfKq1Xdu34ZCRXG2bROeoVQVA==,iv:EewOJ7tVvlg7YRk1cyPQOyr6vX/sRc+waKVca8rhIyM=,tag:4bT59VpZ+XUkb7z39CURIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQnVxRDV6c2J2bjUxWStL
            YzF3TDFDVWtGQ0p6Qm9iYlF0WXRhRlRFa3hNClU2NTFqMDZaRzFBTkIwZlE1Z2g5
            U1NsQ1JZOHEvbDRXaGtkME9EdStwejAKLS0tIDI5amVCVTRjaGtlMnczSGJBWC9a
            b0hCQTNMdGpnYXVvWmR4Q2d2T240VzAKgId5W5u4THywzlaYDZTlF0wuGD3R4ncz
            j8gLz1y2VYyFJVWk7qwu9FLNMnB9SXnbDhrb/O9SsiARF6CeOpwFew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T07:03:46Z"
    mac: ENC[AES256_GCM,data:GQIFNChSJFgvPZC2vXA16NLixfdY9cqJBYOIRI8T9L/XCB5oIMr+6/qAIuZMW0So/YKAnSIA9iOgmzlzslc3gSDNQSRQjbzogdX4fGR4KU8q/h3HB6nWLL8/cCzZQh8SjKTgCAppM9f/VAxovKaRarA/N+u2717TKLhCSFMugPQ=,iv:kq1k0BIIni+52Q1W39o2YMMDRtHxvxP859UyEmRUbr0=,tag:6YTQ0yD7OKysbgttyP9NCA==,type:str]
    version: 3.13.1
