apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ggBJAnjP1QdOgmWS0wpwOWGceHJYxg3MCW7H,iv:9ugs08gmX3OanHuEUI8TUfrZTcxA3VhreIim1IKpyGw=,tag:t3eugEiz4/7fZZkkDMibhA==,type:comment]
    #ENC[AES256_GCM,data:kRTtaoSrzX1bQxBOWpopPlam2BHFVxA13gMlNyzN1UGPn2YGUddODSlXc8hn/olW/GwqqIrY,iv:xQbwJmNWdVMS0jFPFbbcSHQBmZZ9CeY4yusoJEs7qkk=,tag:6d0F9ncKfVLZ0YumvYCByw==,type:comment]
    token: ENC[AES256_GCM,data:0WnvfvMzKmbGo+10glyQOmAX6oDl4WOMbP1mKmFvs6LbW3NV0XKOLZigcvJxgw==,iv:4wrV0QSsMR5eeDgaJVrQFuLd3Bzc3vZ7Gq/IYi6SNwU=,tag:pFmBsJ8n6/4/NZCNCVJaoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z09PUThlR3lqYmhJUWJm
            KzIwNm14ZGxOdGQ4YXFlVUw5dXNSUUFkQkFJClpmeFpmOUdORTBHaTl0NDB5ZEM4
            Z2ttSWRPejB0Z1VDdmZFNG5pRlpFN1kKLS0tIExKWGZoelY2ZHQ5RUdqWStOdEVP
            bXFNeTV4bncweVJ0OW9PYXgyZ3l3Q1UKytjs8NyktXwOuy6grjtG5rglChxvwbW2
            XI1GOJ9Pb8dF0SUCd9vXG/zXmpZG394SLa1p/N7FazhrlS+xRm/sBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T09:09:34Z"
    mac: ENC[AES256_GCM,data:guZruIOrSZ5atEPDhMFcVz5tQhgq6+yMomjHIcKAgJWldK98KGh3JMoz4T/ZIVUDhCehiw5krSNoVIo9ve+NWCjvZGM8LipVJwzbb6zc2CFuAUxYH3d33/GYeeQkT44JCCCyzaOynf597Gi6ZRSzQJtJMTs3EruG0vrn8q7K7mA=,iv:4A2G0Nv8U5zigur3rJUzbj1ggE/BmmE/z48JYzSCfjk=,tag:M68srP1tZ6KnrTsbHxBe1Q==,type:str]
    version: 3.13.1
