apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: asp
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:WXS5eAVzDRaCTjraouObEW2RyOW+k/BzG0+3oacKJy/mYn8SCS5oF1hNlU94ad0+pbBVPx7NjP/ztdk94MtqNJ2yPYJtLbzq3flsY7OBQq74MtctbOVO82T8YXUSPKm7aB38cfcpeKJa3NHNmjxxj7VeHUc2vfNeoFFjHCNq96WMpSzNAt4vIMTINKpeRFTbiB+GZ4c47iMfuOqLf94HLbxqC2X4KwAY6n2dAElA5uqy,iv:auX9D+dH17R3/6kNOReiS6jTAOCZmA0mmDHQR20r3iY=,tag:78yHyDPWmbqwTubBPKPiRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZnZPL3Z4MWxvQmV6R2o4
            VzAvbGlUUmRZRzVRNzc5cGhMUnBXUWorQ3pRCkgxTCsreEcwUVA5SkY0UmppcDV3
            MVJhSlU5djhkQllwa0cwREFBZ210d28KLS0tIDlzWXR3c01ob0tZek1BUVRQS1Qy
            WnUyL2puaHVqb3B5ekhhNnNVNTBvbTgKecUd61UWM1qaz0vBArGfJK8A6XaWXKAw
            OUnmjmH/qhz+hB6qmoigI1669T5uYTxH9ZXo0DfhGd78MWRJJN195Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heestkhtxgn5afg9jdww4dpxlk39qztjgcanu8pr4g8usufww36sdx732h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T10:40:56Z"
    mac: ENC[AES256_GCM,data:p1OW5kBlhS+R50KgB+glPXYw+OfVR3VT2lqnthI25+Bsx4B+sX8iSwJHZG97kl5IU3Dkd5gEh9JxqX/5v+4KNFlsow9aGp8031XrxSAbDuKNDYSBaNbdXyRXqnhZI2YxpY7S6SgWp/905r4t3eHkozo2Xr0DCKy7N7mJI5Y1cYc=,iv:kyacIuVcarh/htgd7UJhwC9F7sktZOQDwpLS9mXj1d0=,tag:8xy0VU7oF4GC/GR+msWvXQ==,type:str]
    version: 3.13.1
