apiVersion: v1
kind: Secret
metadata:
    name: orchestrator-secrets
    namespace: asp
type: Opaque
stringData:
    admin-ui-token: ENC[AES256_GCM,data:vj2iMBjp+0+m61O9VXWQ2DeZ+yWBjsfnpJjZmCLSKw5ewXuDzY0z2PPHoBzLUyRK,iv:uIN1D2BSdoWfatgS70/VyUljz+ewAnZhS8HGXQPDDyQ=,tag:iEHD+nyRnR/I/k8y0vcT4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNGluZGFCT1o5b1p4bTJq
            ai82YlBveHZSdDUrOExTeE5NcDBCMlFoM21ZClpoWmxyeHpheHh1Z1VsM2lGR1ZD
            YS9hQUh5S0xJTGZ2NmdtY3FhMzNjZDgKLS0tIHJQWUVhSDltbWN2Z2l4SWpnS0c2
            dUR3UTVhQlNsdFJweUdKSHoyeUZEZzgKN/WFTqWRZYL9SId5Wxjoq2QJxx7KBN9Z
            NHi3aZkfmKI0XcB3tQkQdbbdXQNYRIhf6C3aO9Yp9FJgCakWYQB/VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heestkhtxgn5afg9jdww4dpxlk39qztjgcanu8pr4g8usufww36sdx732h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T09:07:36Z"
    mac: ENC[AES256_GCM,data:DgEB5Ki8KqnN/nUwWPjprL5n7ObUZlrao7ngHcvIAmjN+zQE8ZvQiwEtjbVpBpC2pP5/BpryFpwffrWj3ez2esp2imQehtpwguxR0eP7pkhfM59AzrE4EhE3iArU/dc9acXlL9nCW7sPNhCwZBvCPkDTaRzqsvHEIXfqtzKKGNs=,iv:qqsjqA+Hu8aB88uZv4NdN4nnCOFx27NLXbIT3JkpRW4=,tag:HmPHt4OgXJz4oazKCjdoww==,type:str]
    version: 3.13.1
