apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:k6gk4peUkkDKubHMi7R10177MzAZdFC+V1n3+Y+iCiUfqOWu5ER28PokJSoHhGGAhudp5fkd52A=,iv:Ch3NW9JJ+87IJR3GSNDF3TYQE5276fG/maoTZvPWVU0=,tag:zDLVo/93K7TI5UJvay/47w==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL2ZHcUJjRXlodENiTGh2
            SmdQZ1ZFRXMwUTAvZGxXQ2YxN2NYcmdtMWlvCmlXdkttVStib3VGVzVzaDVWYWJO
            OWl4UG41K29hS0lWeUlsaFk2di9jMGsKLS0tIGlZc0g4bllTZUFocjRZejEyd0s3
            WTlZZHV3YXpjM21NUnBVQTcybUZOVDgKRptt8TZ2FF07O4BsHYLiEwRLk0FsWIYy
            4M0NB9Ru0vyeMptoLRg6ef8KJtNHmLUpaSBVwIyRztN1CSJ8tTJAQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T15:12:26Z"
    mac: ENC[AES256_GCM,data:uQSfDOdpjkZgbKDWz6+E3eyVkcRFh6IuMLvLlhlIexWkRW9FOe/TyvbzMI9K+F1a1ljidqE7nMXdikHrfU2Fq2k96tdy5CSFNATokFVhm6X0nC3ssUfdeItoYYSQ821BPRtJ4K80abFzCuelDyvzs3f7j4U4m2OSN7qErBuEGmA=,iv:e8G3xKv+fCjSqhAumIHKojZ5lJaE0ZDloa8pSMcPSic=,tag:0P5eZcaG+AN3LH6h6AiZHQ==,type:str]
    encrypted_regex: ^(data|stringDate)$
    version: 3.11.0
